'use strict';

/**
 * htmlGen.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Pure deterministic renderer.  Takes a SlideModel from slideBuilder.js and
 * emits an HTML string representing one slide at 1333×750.
 *
 * Rules:
 *   - NO layout decisions made here
 *   - NO pixel coordinates decided here
 *   - ALL values come from the SlideModel
 *   - Text rendered as plain HTML (no arbitrary CSS generated by AI)
 *   - Images rendered with explicit crop/position from SlideModel
 *   - Overlays rendered as CSS gradient or solid, exactly as specified
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ─── Theme / design tokens ────────────────────────────────────────────────────
// Default theme; override by passing `theme` to renderSlide()
const DEFAULT_THEME = {
  fontFamily:       "'Inter', 'Helvetica Neue', Arial, sans-serif",
  colorBg:          '#ffffff',
  colorText:        '#111111',
  colorTextMuted:   '#555555',
  colorAccent:      '#2563EB',
  colorSidebar:     '#1E1E2E',
  colorSidebarText: '#E2E8F0',
  colorCard:        '#ffffff',
  colorCardText:    '#111111',
  quoteMarkColor:   '#2563EB',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function px(val) { return `${val}px`; }

function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Convert a zone definition to absolute-positioned CSS properties.
 */
function zoneToStyle(zone, extra = {}) {
  const base = {
    position:  'absolute',
    left:      px(zone.x),
    top:       px(zone.y),
    width:     px(zone.w),
    height:    px(zone.h),
    boxSizing: 'border-box',
    overflow:  'hidden',
    ...extra,
  };
  return cssString(base);
}

function cssString(obj) {
  return Object.entries(obj)
    .map(([k, v]) => `${kebab(k)}: ${v}`)
    .join('; ');
}

function kebab(camel) {
  return camel.replace(/([A-Z])/g, m => `-${m.toLowerCase()}`);
}

// ─── Overlay renderer ─────────────────────────────────────────────────────────
function renderOverlay(overlay, zone) {
  if (!overlay || overlay.type === 'none') return '';

  let style = `
    position: absolute;
    left: ${px(zone.x)}; top: ${px(zone.y)};
    width: ${px(zone.w)}; height: ${px(zone.h)};
    pointer-events: none;
  `;

  if (overlay.type === 'gradient') {
    const dir = overlay.direction === 'bottom-to-top' ? 'to top' : 'to bottom';
    style += `background: linear-gradient(${dir},
      rgba(0,0,0,${overlay.opacity}) 0%,
      rgba(0,0,0,0) 100%);`;
  } else if (overlay.type === 'solid') {
    style += `background: rgba(0,0,0,${overlay.opacity});`;
  } else if (overlay.type === 'blur') {
    style += `
      background: rgba(0,0,0,${overlay.opacity});
      backdrop-filter: blur(${overlay.blur}px);
      -webkit-backdrop-filter: blur(${overlay.blur}px);
    `;
  }

  return `<div style="${style}"></div>`;
}

// ─── Zone renderers ───────────────────────────────────────────────────────────

function renderImageZone(zoneName, zone, imageSrc, theme) {
  if (!imageSrc) {
    // Placeholder when image not yet fetched
    const style = zoneToStyle(zone, {
      background:     '#e5e7eb',
      display:        'flex',
      alignItems:     'center',
      justifyContent: 'center',
      borderRadius:   zone.borderRadius ? px(zone.borderRadius) : undefined,
    });
    return `<div style="${style}" data-zone="${zoneName}" data-role="image-placeholder">
      <span style="color:#9ca3af;font-size:14px;font-family:sans-serif;">
        ${escapeHtml(zoneName)}
      </span>
    </div>`;
  }

  // Border-radius: handle circular portraits
  const br = zone.borderRadius === 1000 ? '50%' :
             zone.borderRadius ? px(zone.borderRadius) : '0';

  // Image sizing: cover vs contain
  const objectFit      = zone.crop     || 'cover';
  const objectPosition = zone.position || 'center';

  const imgStyle = `
    position: absolute;
    left: 0; top: 0; width: 100%; height: 100%;
    object-fit: ${objectFit};
    object-position: ${objectPosition};
    border-radius: ${br};
    display: block;
  `;

  const wrapStyle = zoneToStyle(zone, {
    borderRadius: br,
    ...(zone.dropShadow ? { boxShadow: '0 8px 40px rgba(0,0,0,0.30)' } : {}),
  });

  const overlay = zone.overlay ? renderOverlay(zone.overlay, { x: 0, y: 0, w: zone.w, h: zone.h }) : '';

  return `<div style="${wrapStyle}" data-zone="${zoneName}">
    <img src="${escapeHtml(imageSrc)}" alt="" style="${imgStyle}" loading="lazy" />
    ${overlay}
  </div>`;
}

function renderTextZone(zoneName, zone, content, theme) {
  if (!content) return '';

  const textColor = zone.color || theme.colorText;

  const style = zoneToStyle(zone, {
    display:        'flex',
    flexDirection:  'column',
    justifyContent: 'flex-start',
    alignItems:     zone.align === 'center' ? 'center' : 'flex-start',
  });

  const textStyle = `
    font-family: ${theme.fontFamily};
    font-size: ${px(zone.fontSize)};
    font-weight: ${zone.fontWeight || 400};
    font-style: ${zone.fontStyle || 'normal'};
    color: ${textColor};
    text-align: ${zone.align || 'left'};
    line-height: ${zone.lineHeight || 1.25};
    letter-spacing: -0.01em;
    margin: 0; padding: 0;
    ${zone.textTransform ? `text-transform: ${zone.textTransform};` : ''}
    word-break: break-word;
    overflow-wrap: break-word;
  `;

  return `<div style="${style}" data-zone="${zoneName}">
    <p style="${textStyle}">${escapeHtml(content)}</p>
  </div>`;
}

function renderCardZone(zoneName, zone, theme) {
  const bg = zone.backgroundColor || theme.colorCard;
  const style = zoneToStyle(zone, {
    background:   bg,
    opacity:      zone.opacity != null ? zone.opacity : 1,
    borderRadius: zone.borderRadius ? px(zone.borderRadius) : '0',
  });
  return `<div style="${style}" data-zone="${zoneName}"></div>`;
}

function renderDecoratorZone(zoneName, zone, theme) {
  if (zone.decoration === 'quotemark') {
    const style = zoneToStyle(zone, {
      display:        'flex',
      alignItems:     'flex-start',
      justifyContent: 'flex-start',
    });
    return `<div style="${style}" data-zone="${zoneName}">
      <span style="
        font-size: ${px(zone.fontSize || 180)};
        color: ${zone.color || theme.quoteMarkColor};
        font-family: Georgia, serif;
        line-height: 1;
        opacity: 0.20;
        user-select: none;
        pointer-events: none;
      ">&ldquo;</span>
    </div>`;
  }
  return '';
}

function renderSidebarZone(zoneName, zone, theme) {
  const style = zoneToStyle(zone, {
    background: theme.colorSidebar,
  });
  return `<div style="${style}" data-zone="${zoneName}"></div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN RENDERER
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Render a single slide to HTML.
 *
 * @param {SlideModel} slideModel
 * @param {object}     imageMap     { [zoneName]: 'https://...' }  resolved URLs
 * @param {object}     [theme]      Optional theme overrides
 * @returns {string}   HTML string for this slide
 */
function renderSlide(slideModel, imageMap = {}, theme = {}) {
  const t = { ...DEFAULT_THEME, ...theme };
  const { canvas, zones, layers, background, layoutId, slideId } = slideModel;

  // ── Background resolution ────────────────────────────────────────────────
  // When background.type === 'image' and imageMap.background is set,
  // apply it as a CSS background-image on the slide wrapper.
  // The 'bg-image' class lets renderer.js detect it via .bg-image selector.
  // If no URL is available, use fallbackColor only (no broken bg-image).
  const hasBgImage =
    background?.type === 'image' && imageMap.background;

  const bgColor = background?.type === 'image'
    ? (background.fallbackColor || '#111111')
    : t.colorBg;

  const wrapClass = hasBgImage ? 'slide bg-image' : 'slide';

  const wrapStyle = `
    position: relative;
    width: ${px(canvas.w)};
    height: ${px(canvas.h)};
    overflow: hidden;
    background-color: ${bgColor};
    ${hasBgImage
      ? `background-image: url("${escapeHtml(imageMap.background)}");
    background-size: cover;
    background-position: center;`
      : ''}
    font-family: ${t.fontFamily};
    box-sizing: border-box;
  `;

  // Build HTML for each zone in z-index order
  const layerOrder = (layers || []).map(l => l.zone);
  const allZoneNames = [...new Set([...layerOrder, ...Object.keys(zones)])];

  const zoneHtml = allZoneNames.map(zoneName => {
    const zone = zones[zoneName];
    if (!zone) return '';

    switch (zone.type) {
      case 'image':
        return renderImageZone(zoneName, zone, imageMap[zoneName] || null, t);

      case 'text':
        return renderTextZone(zoneName, zone, zone.content, t);

      case 'card':
        // card_bg is rendered first (lower z), text zones render above it
        if (zoneName === 'sidebar_bg') return renderSidebarZone(zoneName, zone, t);
        return renderCardZone(zoneName, zone, t);

      case 'decorator':
        return renderDecoratorZone(zoneName, zone, t);

      default:
        return '';
    }
  }).join('\n  ');

  return `<div class="${wrapClass}" id="${escapeHtml(slideId)}" data-layout="${escapeHtml(layoutId)}"
       style="${wrapStyle}">
  ${zoneHtml}
</div>`;
}

/**
 * Render a complete deck to a full HTML page.
 *
 * @param {SlideModel[]} deck
 * @param {object[]}     imageMaps   One imageMap per slide
 * @param {object}       [theme]
 * @returns {string}     Full HTML document
 */
function renderDeck(deck, imageMaps = [], theme = {}) {
  const slides = deck
    .map((model, i) => renderSlide(model, imageMaps[i] || {}, theme))
    .join('\n\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Presentation</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #1a1a1a; display: flex; flex-direction: column;
           align-items: center; padding: 40px; gap: 24px; }
    .slide { flex-shrink: 0; box-shadow: 0 4px 40px rgba(0,0,0,0.4); }
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800;900&display=swap');
  </style>
</head>
<body>
${slides}
</body>
</html>`;
}

module.exports = { renderSlide, renderDeck, DEFAULT_THEME };
